# Site
site_name: Software Handbook
site_description: A handbook about Software Engineering, Data and AI
site_author: locch
site_url: https://locchh.github.io/sw-handbook/

# Repository
repo_url: https://github.com/locchh/sw-handbook
repo_name: locch/sw-handbook
edit_uri: edit/main/docs/

# Theme
theme:
  name: material
  palette:
    # Darker color scheme
    primary: indigo
    accent: blue
  font:
    text: Roboto Mono
    code: Roboto Mono
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.indexes
    - navigation.sections
    - content.code.copy

# Markdown extensions
markdown_extensions:
  - admonition
  - pymdownx.highlight
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed
  - pymdownx.details
  - toc:
      permalink: true

# Extra JavaScript
extra_javascript:
  - https://unpkg.com/mermaid@10.9.1/dist/mermaid.min.js
  - javascripts/mermaid-init.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - javascripts/mathjax-init.js
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

# Navigation
nav:
  - Home: index.md
  - Software:
      - Overview: software/index.md
      - Fundamentals:
        - Basic Concepts: software/basics/basic_concepts.md
        - Development Concepts: software/basics/devlopment_concepts.md
        - Coding Philosophies: software/basics/philosophies_principles.md
        - Architecture Patterns: software/basics/architecture_patterns.md
        - Styles: software/basics/styles.md
        - Abbreviations: software/basics/abbreviations.md
        - Study Guide: software/basics/study_guide.md
      - Tool/Tip:
        - Tools: software/tool_tip/tools.md
        - Tips: software/tool_tip/tips.md
  - Data:
      - Overview: data/index.md
      - Fundamentals:
          - Introduction to Data: data/basics/introduction_to_data.md
  - AI:
      - Overview: ai/index.md
      - Fundamentals:
          - Concepts: ai/basics/concepts.md
          - Posts: ai/basics/posts.md
  - About: about.md